// <auto-generated />
using System;
using System.Collections.Generic;
using LetsTripTogether.InternalApi.Infrastructure.EntityFramework.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace WebApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251106181910_UniqueRoleName")]
    partial class UniqueRoleName
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LetsTripTogether.InternalApi.Domain.Aggregates.DestinationAggregate.Entities.Destination", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Destinations", (string)null);
                });

            modelBuilder.Entity("LetsTripTogether.InternalApi.Domain.Aggregates.DestinationAggregate.Entities.DestinationAttraction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("character varying(35)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid>("DestinationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("character varying(70)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DestinationId");

                    b.ToTable("DestinationAttractions", (string)null);
                });

            modelBuilder.Entity("LetsTripTogether.InternalApi.Domain.Aggregates.GroupAggregate.Entities.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("TripExpectedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Groups", (string)null);
                });

            modelBuilder.Entity("LetsTripTogether.InternalApi.Domain.Aggregates.GroupAggregate.Entities.GroupInvitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("GroupInvitations", (string)null);
                });

            modelBuilder.Entity("LetsTripTogether.InternalApi.Domain.Aggregates.GroupAggregate.Entities.GroupMatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DestinationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DestinationId");

                    b.HasIndex("GroupId");

                    b.ToTable("GroupMatches", (string)null);
                });

            modelBuilder.Entity("LetsTripTogether.InternalApi.Domain.Aggregates.GroupAggregate.Entities.GroupMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsOwner")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("UserId");

                    b.ToTable("GroupMembers", (string)null);
                });

            modelBuilder.Entity("LetsTripTogether.InternalApi.Domain.Aggregates.GroupAggregate.Entities.GroupMemberDestinationVote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DestinationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GroupMemberId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DestinationId");

                    b.HasIndex("GroupMemberId");

                    b.ToTable("GroupMemberDestinationVotes", (string)null);
                });

            modelBuilder.Entity("LetsTripTogether.InternalApi.Domain.Aggregates.GroupAggregate.Entities.GroupPreference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<bool>("LikesCommercial")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.PrimitiveCollection<List<string>>("_culture")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("Culture");

                    b.PrimitiveCollection<List<string>>("_entertainment")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("Entertainment");

                    b.PrimitiveCollection<List<string>>("_food")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("Food");

                    b.PrimitiveCollection<List<string>>("_placeTypes")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("PlaceTypes");

                    b.HasKey("Id");

                    b.HasIndex("GroupId")
                        .IsUnique();

                    b.ToTable("GroupPreferences", (string)null);
                });

            modelBuilder.Entity("LetsTripTogether.InternalApi.Domain.Aggregates.RoleAggregate.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("LetsTripTogether.InternalApi.Domain.Aggregates.UserAggregate.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)");

                    b.Property<bool>("IsAnonymous")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("LetsTripTogether.InternalApi.Domain.Aggregates.UserAggregate.Entities.UserGroupInvitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GroupInvitationId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsAccepted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GroupInvitationId");

                    b.HasIndex("UserId");

                    b.ToTable("UserGroupInvitations", (string)null);
                });

            modelBuilder.Entity("LetsTripTogether.InternalApi.Domain.Aggregates.UserAggregate.Entities.UserPreference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("LikesCommercial")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<List<string>>("_culture")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("Culture");

                    b.PrimitiveCollection<List<string>>("_entertainment")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("Entertainment");

                    b.PrimitiveCollection<List<string>>("_food")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("Food");

                    b.PrimitiveCollection<List<string>>("_placeTypes")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("PlaceTypes");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserPreferences", (string)null);
                });

            modelBuilder.Entity("LetsTripTogether.InternalApi.Domain.Aggregates.UserAggregate.Entities.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("LetsTripTogether.InternalApi.Domain.Aggregates.DestinationAggregate.Entities.DestinationAttraction", b =>
                {
                    b.HasOne("LetsTripTogether.InternalApi.Domain.Aggregates.DestinationAggregate.Entities.Destination", "Destination")
                        .WithMany("Attractions")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Destination");
                });

            modelBuilder.Entity("LetsTripTogether.InternalApi.Domain.Aggregates.GroupAggregate.Entities.GroupInvitation", b =>
                {
                    b.HasOne("LetsTripTogether.InternalApi.Domain.Aggregates.GroupAggregate.Entities.Group", "Group")
                        .WithMany("Invitations")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("LetsTripTogether.InternalApi.Domain.Aggregates.GroupAggregate.Entities.GroupMatch", b =>
                {
                    b.HasOne("LetsTripTogether.InternalApi.Domain.Aggregates.DestinationAggregate.Entities.Destination", "Destination")
                        .WithMany("GroupMatches")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LetsTripTogether.InternalApi.Domain.Aggregates.GroupAggregate.Entities.Group", "Group")
                        .WithMany("Matches")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Destination");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("LetsTripTogether.InternalApi.Domain.Aggregates.GroupAggregate.Entities.GroupMember", b =>
                {
                    b.HasOne("LetsTripTogether.InternalApi.Domain.Aggregates.GroupAggregate.Entities.Group", "Group")
                        .WithMany("Members")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LetsTripTogether.InternalApi.Domain.Aggregates.UserAggregate.Entities.User", "User")
                        .WithMany("GroupMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LetsTripTogether.InternalApi.Domain.Aggregates.GroupAggregate.Entities.GroupMemberDestinationVote", b =>
                {
                    b.HasOne("LetsTripTogether.InternalApi.Domain.Aggregates.DestinationAggregate.Entities.Destination", "Destination")
                        .WithMany("GroupMemberVotes")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LetsTripTogether.InternalApi.Domain.Aggregates.GroupAggregate.Entities.GroupMember", "GroupMember")
                        .WithMany("Votes")
                        .HasForeignKey("GroupMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Destination");

                    b.Navigation("GroupMember");
                });

            modelBuilder.Entity("LetsTripTogether.InternalApi.Domain.Aggregates.GroupAggregate.Entities.GroupPreference", b =>
                {
                    b.HasOne("LetsTripTogether.InternalApi.Domain.Aggregates.GroupAggregate.Entities.Group", "Group")
                        .WithOne("Preferences")
                        .HasForeignKey("LetsTripTogether.InternalApi.Domain.Aggregates.GroupAggregate.Entities.GroupPreference", "GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("LetsTripTogether.InternalApi.Domain.Aggregates.UserAggregate.Entities.UserGroupInvitation", b =>
                {
                    b.HasOne("LetsTripTogether.InternalApi.Domain.Aggregates.GroupAggregate.Entities.GroupInvitation", "GroupInvitation")
                        .WithMany("AnsweredBy")
                        .HasForeignKey("GroupInvitationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LetsTripTogether.InternalApi.Domain.Aggregates.UserAggregate.Entities.User", "User")
                        .WithMany("AcceptedInvitations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GroupInvitation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LetsTripTogether.InternalApi.Domain.Aggregates.UserAggregate.Entities.UserPreference", b =>
                {
                    b.HasOne("LetsTripTogether.InternalApi.Domain.Aggregates.UserAggregate.Entities.User", "User")
                        .WithOne("Preferences")
                        .HasForeignKey("LetsTripTogether.InternalApi.Domain.Aggregates.UserAggregate.Entities.UserPreference", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LetsTripTogether.InternalApi.Domain.Aggregates.UserAggregate.Entities.UserRole", b =>
                {
                    b.HasOne("LetsTripTogether.InternalApi.Domain.Aggregates.RoleAggregate.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LetsTripTogether.InternalApi.Domain.Aggregates.UserAggregate.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LetsTripTogether.InternalApi.Domain.Aggregates.DestinationAggregate.Entities.Destination", b =>
                {
                    b.Navigation("Attractions");

                    b.Navigation("GroupMatches");

                    b.Navigation("GroupMemberVotes");
                });

            modelBuilder.Entity("LetsTripTogether.InternalApi.Domain.Aggregates.GroupAggregate.Entities.Group", b =>
                {
                    b.Navigation("Invitations");

                    b.Navigation("Matches");

                    b.Navigation("Members");

                    b.Navigation("Preferences")
                        .IsRequired();
                });

            modelBuilder.Entity("LetsTripTogether.InternalApi.Domain.Aggregates.GroupAggregate.Entities.GroupInvitation", b =>
                {
                    b.Navigation("AnsweredBy");
                });

            modelBuilder.Entity("LetsTripTogether.InternalApi.Domain.Aggregates.GroupAggregate.Entities.GroupMember", b =>
                {
                    b.Navigation("Votes");
                });

            modelBuilder.Entity("LetsTripTogether.InternalApi.Domain.Aggregates.RoleAggregate.Entities.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("LetsTripTogether.InternalApi.Domain.Aggregates.UserAggregate.Entities.User", b =>
                {
                    b.Navigation("AcceptedInvitations");

                    b.Navigation("GroupMemberships");

                    b.Navigation("Preferences");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
